version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    ignore:
      - dependency-name: "@types/node"
        versions:
          - "> 12.12.11"
      - dependency-name: "@types/vscode"
        versions:
          - "> 1.40.0, < 1.41"
    groups:
      - dependencies:
          patterns:
            - "*"
