version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: typescript
    versions:
    - "> 3.7.2"
  - dependency-name: "@types/node"
    versions:
    - "> 12.12.11"
  - dependency-name: "@types/node"
    versions:
    - "> 12.12.11, < 12.13"
  - dependency-name: "@types/vscode"
    versions:
    - "> 1.40.0"
  - dependency-name: "@types/vscode"
    versions:
    - "> 1.40.0, < 1.41"
