name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    name: Node ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test (Linux)
        run: xvfb-run -a npm test
        if: runner.os == 'Linux'

      - name: Test (non-Linux)
        run: npm test
        if: runner.os != 'Linux'

      - name: Vscode package plugin
        uses: JCofman/vscodeaction@master
        with:
          args: package -o package.vsix

      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: package.vsix

  release:
    if: startsWith(github.ref, 'refs/tags/v') && !endsWith(github.ref, '-pre')
    needs: build
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v1

      - uses: actions/download-artifact@v2
        with:
          name: package

      - name: Vscode release plugin
        uses: JCofman/vscodeaction@master
        env:
          PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
        with:
          args: publish -p $PUBLISHER_TOKEN -i package.vsix

  pre-release:
    if: endsWith(github.ref, '-pre')
    needs: build
    runs-on: ubuntu-latest
    name: Pre-release
    steps:
      - uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - run: npm install

      - name: Vscode release plugin
        uses: JCofman/vscodeaction@master
        env:
          PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
        with:
          args: publish -p $PUBLISHER_TOKEN --pre-release
