name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v1
        
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: npm install
        
      - name: Lint
        uses: mooyoul/tslint-actions@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '*.ts'

      - name: Vscode package plugin
        uses: JCofman/vscodeaction@master
        with:
          args: package
      
